name: Run News Scraper and Send to n8n

on:
  workflow_dispatch:
    inputs:
      resumeUrl:
        description: 'n8n Webhook URL to signal completion'
        required: true
        type: string

jobs:
  scrape:
    runs-on: ubuntu-latest
    # env: (Ya no necesitamos WEBHOOK_URL aquí)
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scraper
        run: |
          python3 news_scraper.py > out.json

      - name: Post results to n8n (using resumeUrl)
        run: |
          RESUME_URL=${{ github.event.inputs.resumeUrl }}

          if [ -z "$RESUME_URL" ]; then
            echo "Error: resumeUrl no fue proporcionado. Cayendo en modo standalone."
            exit 0 # Salir con éxito para no fallar el workflow en GitHub, si se dispara manualmente
          fi

          curl -sS -X POST "$RESUME_URL" \
               -H "Content-Type: application/json" \
               --data-binary @out.json
